#!/usr/bin/env bash
# First-run setup for an on-premise Ubuntu server.
#
# Generates the secrets, writes .env.production, builds the images and starts
# the stack. Safe to re-run: an existing .env.production is never overwritten,
# because regenerating PAYLINK_ENCRYPTION_KEY would make every stored gateway
# credential unreadable.
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=.env.production

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m !! %s\033[0m\n' "$*"; }
die()  { printf '\033[31m !! %s\033[0m\n' "$*" >&2; exit 1; }

say "Checking prerequisites"
command -v docker >/dev/null 2>&1 || die "docker is not installed. sudo apt install -y docker.io docker-compose-plugin"
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing. sudo apt install -y docker-compose-plugin"
docker info >/dev/null 2>&1 || die "cannot talk to the docker daemon. Try: sudo usermod -aG docker $USER && newgrp docker"
command -v openssl >/dev/null 2>&1 || die "openssl is not installed. sudo apt install -y openssl"
echo "    docker $(docker version --format '{{.Server.Version}}'), compose present"

if [ -f "$ENV_FILE" ]; then
  say "$ENV_FILE already exists — keeping it"
  warn "Delete it by hand if you truly want fresh secrets. Regenerating"
  warn "PAYLINK_ENCRYPTION_KEY makes every stored MPGS credential unreadable."
else
  say "Configuring"

  read -rp "    Hostname or IP this will be served on (e.g. 10.1.2.136): " HOSTNAME_IN
  [ -n "$HOSTNAME_IN" ] || die "a hostname or IP is required — the certificate is issued for it"

  read -rp "    Port to publish [2000]: " PORT_IN
  PORT_IN=${PORT_IN:-2000}
  case "$PORT_IN" in
    ''|*[!0-9]*) die "the port must be a number" ;;
  esac
  # Refuse a port something else already holds, rather than letting the stack
  # fail halfway up and leave half of it running.
  if command -v ss >/dev/null 2>&1 && ss -tln 2>/dev/null | grep -qE "[:.]$PORT_IN\s"; then
    die "port $PORT_IN is already in use on this host — choose another"
  fi

  cat <<'MODES'

    How should HTTPS be provided?

      1) Our own certificate   you have cert.pem and key.pem for this address
      2) Internal CA           self-signed; every browser warns until Caddy's
                               root is trusted. Internal pilot only.

    HTTPS is not optional: browsers withhold WebCrypto outside a secure
    context, and without it the portal cannot open the sealed channel the API
    requires. Let's Encrypt is not offered because its challenges need port 80
    or 443, and this deployment publishes neither.

MODES
  read -rp "    Choose 1 or 2 [2]: " TLS_MODE
  TLS_MODE=${TLS_MODE:-2}
  case "$TLS_MODE" in
    1) mkdir -p certs
       [ -f certs/cert.pem ] && [ -f certs/key.pem ] \
         || die "put cert.pem and key.pem in ./certs first"
       TLS_VALUE="/certs/cert.pem /certs/key.pem" ;;
    2) TLS_VALUE="internal"
       warn "Self-signed: browsers will warn until Caddy's root certificate is"
       warn "trusted on each device. Get it afterwards with:"
       warn "  docker compose -f docker-compose.prod.yml cp caddy:/data/caddy/pki/authorities/local/root.crt ." ;;
    *) die "choose 1 or 2" ;;
  esac

  read -rp "    Bootstrap password for the 'management' account [generate]: " BOOTSTRAP
  BOOTSTRAP=${BOOTSTRAP:-$(openssl rand -base64 18)}

  say "Generating secrets"
  MYSQL_PASSWORD=$(openssl rand -base64 24 | tr -d '/@" ')
  MYSQL_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '/@" ')
  JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
  # Must decode to exactly 32 bytes — the API refuses to start otherwise.
  ENCRYPTION_KEY=$(openssl rand -base64 32 | tr -d '\n')

  umask 077
  cat > "$ENV_FILE" <<ENVEOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file secret. Back up PAYLINK_ENCRYPTION_KEY somewhere the database
# backup is NOT — together they are the whole system.

PAYLINK_HOSTNAME=$HOSTNAME_IN
PAYLINK_PORT=$PORT_IN
PAYLINK_TLS=$TLS_VALUE

MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

PAYLINK_ENV=production

# The address customers actually open. Pay links and the gateway's return URL
# are both built from it.
PAYLINK_PUBLIC_BASE_URL=https://$HOSTNAME_IN:$PORT_IN
PAYLINK_CORS_ORIGINS=https://$HOSTNAME_IN:$PORT_IN

# Caddy reaches the API over the compose network, and the API believes the
# forwarded header only from these ranges. Widen this and a caller could choose
# their own identity, walking around every rate limit and lockout.
PAYLINK_TRUSTED_PROXIES=172.16.0.0/12,10.0.0.0/8,192.168.0.0/16,127.0.0.0/8

PAYLINK_JWT_SECRET=$JWT_SECRET
PAYLINK_ENCRYPTION_KEY=$ENCRYPTION_KEY
PAYLINK_BOOTSTRAP_PASSWORD=$BOOTSTRAP

# Session policy. TTL is absolute and never extended; IDLE ends a session
# sooner when it is left untouched. An account holds one session at a time.
PAYLINK_SESSION_TTL=15m
PAYLINK_SESSION_IDLE=3m

PAYLINK_GATEWAY_HOST=test-gateway.mastercard.com
PAYLINK_GATEWAY_API_VERSION=100

# Optional outbound email for sharing links.
# PAYLINK_SMTP_HOST=
# PAYLINK_SMTP_PORT=587
# PAYLINK_SMTP_USERNAME=
# PAYLINK_SMTP_PASSWORD=
# PAYLINK_SMTP_FROM=paylink@zemenbank.et
ENVEOF
  chmod 600 "$ENV_FILE"
  echo "    wrote $ENV_FILE (chmod 600)"
fi

# Compose only auto-loads a file literally named ".env" when it expands
# ${MYSQL_PASSWORD} and friends inside the compose file. This script always
# passes --env-file, so the stack starts correctly — but every other command
# that omits the flag fails with "required variable MYSQL_PASSWORD is missing
# a value", which reads like the stack is broken when it is running perfectly.
# Linking the two names makes the documented commands work as written.
if [ -L .env ]; then
  :
elif [ -e .env ]; then
  warn ".env already exists and is not a link to $ENV_FILE."
  warn "Plain 'docker compose' commands may not see your secrets; add"
  warn "  --env-file $ENV_FILE"
else
  ln -s "$ENV_FILE" .env
  echo "    linked .env -> $ENV_FILE (so plain compose commands work)"
fi

say "Building images — first run takes a few minutes"
docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" build

say "Starting"
docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" up -d

say "Waiting for the API to answer"
# Asked through Caddy, over the compose network, because the API image is
# distroless and has no shell or client to ask with. This checks the thing we
# actually care about — that a request reaches the API and comes back.
READY=
for _ in $(seq 1 60); do
  if docker compose -f docker-compose.prod.yml --env-file "$ENV_FILE" \
       exec -T caddy wget -q -O /dev/null http://api:8080/healthz 2>/dev/null; then
    READY=yes
    break
  fi
  sleep 2
done
if [ -z "$READY" ]; then
  warn "the API did not answer within two minutes."
  warn "Look at why before going further:"
  warn "  docker compose -f docker-compose.prod.yml logs api"
fi

HOST=$(grep '^PAYLINK_HOSTNAME=' "$ENV_FILE" | cut -d= -f2-)
PORT=$(grep '^PAYLINK_PORT=' "$ENV_FILE" | cut -d= -f2-)
BOOT=$(grep '^PAYLINK_BOOTSTRAP_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)

cat <<DONE

==> Up.

    Portal      https://$HOST:$PORT
    Sign in     management / $BOOT     ← change this after the first login

    Logs        docker compose -f docker-compose.prod.yml logs -f api
    Stop        docker compose -f docker-compose.prod.yml down
    Backup      bash scripts/backup.sh

    If the page does not load, check in this order:
      1. does $HOST resolve to this server?      dig +short $HOST
      2. is $PORT open in the firewall?          sudo ufw status
      3. what does Caddy say?                    docker compose -f docker-compose.prod.yml logs caddy

DONE
